### ISSUE TITLE
Inquiry about Pre-processing Error in Training TransEDRP on GDSCv2 Dataset

### ISSUE THREAD

**Issue by Kimmm-pzl** [DrugD/TransEDRP#1]
Hello,

I hope this message finds you well. I have successfully executed the process_GDSCv2.py script as per the provided instructions. However, when I attempted to run the main.py function to train TransEDRP on the GDSCv2 dataset, I encountered the following error:

```
Pre-processed data data/GDSCv2/processed/processed/GDSCv2_train_mix_useChirality.pt not found, doing pre-processing...
Traceback (most recent call last):
  File "main.py", line 220, in <module>
    main(model, config, yaml_path)
  File "main.py", line 100, in main
    train_data = TestbedDataset(root=config["dataset_root"], dataset=train_dataset)
  File "/home/TransEDRP/utils.py", line 28, in __init__
    self.process(xd, xt, y,smile_graph)
  File "/home/TransEDRP/utils.py", line 58, in process
    assert (len(xd) == len(xt) and len(xt) == len(y)), "The three lists must be the same length!"
TypeError: object of type 'NoneType' has no len()
```

It appears that process_GDSCv2.py did not generate the required GDSCv2_train_mix_useChirality.pt file. Could you kindly guide me on where I can pre-process and generate the required GDSCv2_train_mix_useChirality.pt file? I would greatly appreciate your assistance in resolving this issue.

Thank you for your time and attention.

Best regards,
Kim

**Comment by DrugD** [comment]
你下载GDSCv2的数据了吗？

**Comment by Kimmm-pzl** [comment]
我通过您提供的Google drive下载了数据集，里面包括了GDSCv2的数据

**Comment by DrugD** [comment]
好的，这是一些中间变量。我会考虑这个问题，稍等这两天会更新一个版本用于自动处理。

**Comment by Kimmm-pzl** [comment]
好的，感谢您的跟进
